# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-01 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(default='', max_length=100, verbose_name='\u6d4b\u8bd5\u7528\u4f8b\u540d\u79f0')),
                ('request_type', models.CharField(default='', max_length=20, verbose_name='\u63a5\u53e3\u8bf7\u6c42\u7c7b\u578b')),
                ('request_param', models.CharField(default='', max_length=300, verbose_name='\u63a5\u53e3\u8bf7\u6c42\u53c2\u6570')),
                ('request_header', models.CharField(default='', max_length=100, verbose_name='\u8bf7\u6c42\u5934')),
                ('isdelete', models.CharField(default=True, max_length=10, verbose_name='\u72b6\u6001')),
                ('expected_result', models.CharField(default='', max_length=300, verbose_name='\u9884\u671f\u7ed3\u679c')),
                ('login_way', models.CharField(default='', max_length=50, verbose_name='\u767b\u9646\u65b9\u5f0f')),
                ('return_result', models.CharField(default='', max_length=300, verbose_name='\u63a5\u53e3\u8fd0\u884c\u8fd4\u56de\u7ed3\u679c')),
                ('case_result', models.CharField(default='', max_length=20, verbose_name='\u7528\u4f8b\u8fd0\u884c\u7ed3\u679c')),
                ('project_name', models.ForeignKey(default='', max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='testcase_project', to='myapp.Project', verbose_name='\u9879\u76ee\u540d\u79f0')),
            ],
        ),
    ]
