# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-12 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportdetail',
            name='test_time',
        ),
        migrations.AddField(
            model_name='reportdetail',
            name='test_time',
            field=models.DateTimeField(null=True, verbose_name='\u7528\u4f8b\u6267\u884c\u65f6\u95f4'),
        ),
    ]
