# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-01 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_result',
            field=models.CharField(default='\u672a\u5f00\u59cb', max_length=20, verbose_name='\u7528\u4f8b\u8fd0\u884c\u7ed3\u679c'),
        ),
    ]
