# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-12 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190112_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='test_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reportdetail',
            name='test_time',
            field=models.CharField(max_length=50, null=True, verbose_name='\u7528\u4f8b\u6267\u884c\u65f6\u95f4'),
        ),
    ]
