# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-13 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190112_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdetail',
            name='case_result',
            field=models.CharField(default='', max_length=500, verbose_name='\u7528\u4f8b\u8fd4\u56de\u7ed3\u679c'),
        ),
        migrations.AddField(
            model_name='reportdetail',
            name='request_type',
            field=models.CharField(default='', max_length=20, verbose_name='\u63a5\u53e3\u8bf7\u6c42\u65b9\u5f0f'),
        ),
    ]
