# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-01 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190101_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='request_header',
            field=models.CharField(default='', max_length=100, verbose_name='\u8bf7\u6c42\u5934'),
        ),
    ]
