# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-13 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190113_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdetail',
            name='case_result',
            field=models.CharField(default='', max_length=6000, verbose_name='\u7528\u4f8b\u8fd4\u56de\u7ed3\u679c'),
        ),
    ]
