# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-20 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20190113_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimingTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='', max_length=100, verbose_name='\u5b9a\u65f6\u4efb\u52a1\u540d\u79f0')),
                ('time', models.CharField(max_length=50, verbose_name='\u5b9a\u65f6\u4efb\u52a1\u6267\u884c\u65f6\u95f4')),
                ('isdelete', models.CharField(default=True, max_length=10, verbose_name='\u5220\u9664\u72b6\u6001')),
                ('is_stop', models.CharField(default=True, max_length=10, verbose_name='\u505c\u7528\u72b6\u6001')),
            ],
        ),
    ]
