# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-20 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_timingtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timingtask',
            name='isdelete',
            field=models.CharField(blank=True, default=True, max_length=10, verbose_name='\u5220\u9664\u72b6\u6001'),
        ),
    ]
